core/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('main.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name='main'
urlpatterns = [
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
    path('home/', HomeView.as_view(), name='home'), 
    # path('contact/', contact, name='contact'),
    path('room/<str:room_name>/', RoomView.as_view(), name='view-room'),
    path('create-room/', createRoom.as_view(), name = 'create-room'),
    path('update-room/<int:pk>/', updateRoom.as_view(), name = 'update-room'),
    path('delete-room/<int:pk>/', deleteRoom.as_view(), name = 'delete-room'),
    path('delete-message/<int:pk>/', deleteMessage.as_view(), name = 'delete-message'),
    path('profile/<str:username>/', UserProfile.as_view(), name = 'user-profile'), 
    path('update-profile/', updateUser.as_view(), name='update-profile'),
    path('topics/', TopicsView.as_view(), name='topics'),
    path('activity/', ActivityView.as_view(), name='activity'),
    # path('search/', search_results, name='ajax-search'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StydyBud course</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    <ul>
        <li><a href="{% url 'main:home' %}">Home</a></li>
        <li><a href="{% url 'main:contact' %}">Contact</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'main:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'main:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'main:register' %}">Register</a></li>
    </ul>
    
    {% if messages %}
        <ul class="messsages">
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'main:home' %}" method="GET" >
        <input type="text" name="q" placeholder = 'Search Rooms...' autocomplete='off'>
    </form>
    <hr>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>