core/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('main.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<int:pk>/', views.getRoom)
]

main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name='main'
urlpatterns = [
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
    path('home/', HomeView.as_view(), name='home'), 
    # path('contact/', contact, name='contact'),
    path('room/<str:room_name>/', RoomView.as_view(), name='view-room'),
    path('create-room/', createRoom.as_view(), name = 'create-room'),
    path('update-room/<int:pk>/', updateRoom.as_view(), name = 'update-room'),
    path('delete-room/<int:pk>/', deleteRoom.as_view(), name = 'delete-room'),
    path('delete-message/<int:pk>/', deleteMessage.as_view(), name = 'delete-message'),
    path('profile/<str:username>/', UserProfile.as_view(), name = 'user-profile'), 
    path('update-profile/', updateUser.as_view(), name='update-profile'),
    path('topics/', TopicsView.as_view(), name='topics'),
    path('activity/', ActivityView.as_view(), name='activity'),
    # path('search/', search_results, name='ajax-search'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

# Create your models here.

class User(AbstractUser):
    # username = models.CharField(max_length = 50)
    name = models.CharField(max_length = 100)
    # email = models.EmailField()
    bio = models.TextField(null=True, blank=True)
    # whenever you specify a default, django looks in the MEDIA_URL directory (which usually is the last bit of the url in the MEDIA_ROOT setting) 
    # the media url is the starting url for the links to the images displayed on the site and it can be named anything 
    # the media url gets its files from the media_root directory, but the name itself is what gets displayed in the urlbar in the website
    # in the settings which is currently 'media/' in the base directory.
    # django starts there and in the case below, we tell django to go further into 'user_images/' to get the image.
    image = models.ImageField(_('avatar'), upload_to = 'user_images', blank=True, null=True, default = 'user_images/default.png')

class Topic(models.Model):
    name = models.CharField(max_length = 200)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, related_name='owned_rooms')
    topic = models.ForeignKey(Topic, on_delete = models.SET_NULL, null = True, related_name = 'discussed_in')
    name = models.CharField(max_length=200)
    description = models.TextField(null = True, blank = True)
    participants = models.ManyToManyField(User, related_name='joined_rooms', blank=True)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'messages')
    room = models.ForeignKey(Room, on_delete = models.CASCADE, related_name = 'messages')
    body = models.TextField()
    updated = models.DateTimeField(auto_now =True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.body[:50]}..."  if len(self.body) > 50 else self.body                           

main/forms.py
from  django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

class MyUserCreationForm(UserCreationForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['image', 'name', 'username', 'email', 'bio', 'password1', 'password2']


class MyUserUpdateForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['image', 'name', 'username', 'email', 'bio']

main/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from main.models import Room
from .serializers import RoomSerializer

# this decorator allows us to use the django rest framework for this view
@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id' 
    ]
    return  Response(routes)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Message, Room, User
from django.views.generic import *
from .forms import *
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import JsonResponse

# Create your views here.

class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('main:home'))
        return render(request, 'main/login-register.html', {'action':'login'})
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'You have logged in successfully as {request.user}')
        else:
            messages.error(request, 'username or pasword does not exist')
        # print(request.META['HTTP_REFERER'])
        return redirect(reverse('main:home'))

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('main:home'))

class RegisterView(View):
    def get(self, request):
        return render(request, 'main/login-register.html', {'action':'register', 'form':MyUserCreationForm()})
    def post(self, request):
        print(request.POST)
        #! always remember to pass in request.FILES when submitting forms that have an Imagefield or any type of filefield
        # ! attached to them
        form = MyUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            # user.username = user.username.lower()
            user.save()
            login(request, user)
        else:
            messages.error(request, 'An error occured during registration')
        return redirect(reverse('main:home'))
        
class RoomView(View):
    def get(self, request, room_name):
        room = Room.objects.get(name=room_name)
        room_messages = room.messages.all()
        participants = room.participants.all()
        return render(request, 'main/room.html', {'room':room, 'room_messages':room_messages, 'participants':participants})
    def post(self, request, room_name):
        room = Room.objects.get(name=room_name)
        message = Message.objects.create(
            user=request.user,
            room = room,
            body = request.POST.get('body'),
        )
        room.participants.add(request.user)
        messages.success(request, 'Your message has been posted successfully!')
        return self.get(request, room_name=room.name)

class HomeView(View):
    template_name = 'main/home.html'
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        rooms = Room.objects.filter(Q(name__icontains=q) | Q(topic__name__icontains=q) | Q(host__username__icontains=q))[:6] 
        messages = Message.objects.filter(Q(room__in=rooms) | Q(room__topic__name__icontains=q))[:5]
        context = {'rooms': rooms, 'activity':messages, 'room_count':len(rooms), 'topics':Topic.objects.all()[:5]}
        return render(request, 'main/home.html', context)

class UserProfile(View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        rooms = user.owned_rooms.all()
        user_messages = user.messages.all()[:5]
        context = {'user':user, 'topics':Topic.objects.all()[:5], 'rooms':rooms, 'activity':user_messages}
        return render(request, 'main/profile.html', context)

class createRoom(LoginRequiredMixin, View):
    def get(self, request):
        context = {'form':RoomForm(), 'action':'create', 'topics':Topic.objects.all()}
        return render(request, 'main/cr_ud-room.html', context)
    def post(self, request, *args, **kwargs):
        topic, created = Topic.objects.get_or_create(name=request.POST.get('topic'))
        Room.objects.create(
            host = request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description')
        )
        # form = RoomForm(request.POST)
        # if form.is_valid():
        #     new_room = form.save(commit=False)
        #     new_room.host = request.user
        #     new_room.save()
        return redirect(reverse('main:home'))

class updateRoom(LoginRequiredMixin, View):
    def get(self, request, pk):
        room = get_object_or_404(Room, id = self.kwargs.get('pk'))
        if request.user != room.host:
            return HttpResponse(f"You are not allowed to edit '<i>{room}</i>' , it belongs to @{room.host.username}")

        form = RoomForm(instance=room)
        
        return render(request, 'main/cr_ud-room.html', {'form':form, 'room':room, 'action':'update', 'topics':Topic.objects.all()})
    def post(self, request, pk): 
        room = get_object_or_404(Room, id = self.kwargs.get('pk'))
        topic, created = Topic.objects.get_or_create(name=request.POST.get('topic'))
        room.topic = topic
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.save()
        return redirect('main:view-room', room.name)

class deleteRoom(LoginRequiredMixin, View):
    template_name = 'main/delete_form.html'
    def get(self, request, pk):
        room = get_object_or_404(Room, id=pk)
        if request.user != room.host:
            return HttpResponse(f"You are not allowed to delete '<i>{room}</i>' , it belongs to @{room.host.username}")
        return render(request, 'main/delete.html', {'object':room})
    def post(self, request, pk):
        room = get_object_or_404(Room, id=pk)
        room.delete()
        return redirect(reverse('main:home'))

class deleteMessage(LoginRequiredMixin, View):
    template_name = 'main/delete_form.html'
    def get(self, request, pk):
        message = get_object_or_404(Message, id=pk)
        if request.user != message.user and request.user != message.room.host :
            return HttpResponse(f"You are not allowed to delete '<i>{message}</i>' , it belongs to @{message.user.username}")
        return render(request, 'main/delete.html', {'object':message})
    def post(self, request, pk):
        message = get_object_or_404(Message, id=pk)
        room = message.room
        if not room.messages.filter(user=message.user):
            room.participants.remove(message.user) 
        message.delete()
        return redirect(reverse('main:view-room', kwargs = {'room_name':room.name}))

class updateUser(LoginRequiredMixin, View):
    def get(self, request):
        form = MyUserUpdateForm(instance=request.user)
        print(form)
        return render(request, 'main/update-user.html', {'form':form})
    def post(self, request):
        form = MyUserUpdateForm(request.POST, request.FILES, instance=request.user)
        print(form)
        if form.is_valid():
            form.save()
        return redirect(reverse('main:user-profile', kwargs={'username':request.user.username}))
        
class TopicsView(View):
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        topics = Topic.objects.filter(Q(name__icontains=q))
        return render(request, 'main/topics.html', {'topics':topics})

class ActivityView(View):
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        rooms = Room.objects.filter(Q(name__icontains=q) | Q(topic__name__icontains=q) | Q(host__username__icontains=q))[:6] 
        activity = Message.objects.filter(Q(room__in=rooms) | Q(room__topic__name__icontains=q))[:5]
        return render(request, 'main/activity.html', {'activity':activity})

"""
class createRoom2(CreateView):
    template_name = 'main/room_form.html'
    form_class = RoomForm
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('main:home')

class updateRoom2(UpdateView):
    template_name = 'main/create-room.html'
    form_class = RoomForm
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    def get_object(self):
        return get_object_or_404(Room, id = self.kwargs.get('pk'))
    def get_success_url(self):
        return reverse('main:home')
"""

main/templates/main/feed_component.html
{% for room in rooms %}
                
<div class="roomListRoom">
    <div class="roomListRoom__header">
    <a href="{% url 'main:user-profile' room.host.username %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
        <img src="{{room.host.image.url}}" />
        </div>
        <span><a href="{% url 'main:user-profile' room.host.username %}">@{{room.host.username}}</a></span>
    </a>
    <div class="roomListRoom__actions">
        <span>{{room.created|timesince}} ago</span>
    </div>
    </div>
    <div class="roomListRoom__content">
    <a href="{% url 'main:view-room' room.name %}">{{room.name}}</a>
    <p>
        {{room.description}}
    </p>
    </div>
    <div class="roomListRoom__meta">
    <a href="{% url 'main:view-room' room.name %}" class="roomListRoom__joined">
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>user-group</title>
        <path
            d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
            d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
            d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
            d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
        </svg>
        {{room.participants.count}} Joined
    </a>
    <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>

<!-- {% if request.user == room.host %}
    <a href='{% url "main:update-room" room.id %}'>
        <button>Edit</button>
    </a>
    <a href="{% url 'main:delete-room' room.id %}">
        <button>Delete</button>
    </a>
{% endif %}

<span><a href="{% url 'main:user-profile' room.host.username %}">@{{room.host.username}}</a></span>
<h3><a href="{% url 'main:view-room' room.name %}">{{room.id}} ~ {{room.name}}</a></h3> 

<small>{{room.topic.name}} | {{room.participants.count}} participants | {{room.messages.count}} messages</small>
<hr> -->
{% endfor %}


















<!-- {% for room in rooms %}
    {% if request.user == room.host %}
        <a href='{% url "main:update-room" room.id %}'>
            <button>Edit</button>
        </a>
        <a href="{% url 'main:delete-room' room.id %}">
            <button>Delete</button>
        </a> 
    {% endif %}
    
    <span><a href="{% url 'main:user-profile' room.host.username %}">@{{room.host.username}}</a></span>
    <h3><a href="{% url 'main:view-room' room.name %}">{{room.id}} ~ {{room.name}}</a></h3> 
    
    <small>{{room.topic.name}} | {{room.participants.count}} participants | {{room.messages.count}} messages</small>
    <hr>
{% endfor %} -->

main/templates/main/home.html
{% extends 'base.html' %}

{% block content %}

    <main class="layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'main/topics_component.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form class="header__search">
                    <label>
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>search</title>
                        <path
                            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                        ></path>
                        </svg>
                        <input placeholder="Search for posts" />
                    </label>
                    </form>
                    <div class="mobile-menuItems">
                    <a class="btn btn--main btn--pill" href="{% url 'main:topics' %}">Browse Topics</a>
                    <a class="btn btn--main btn--pill" href="{% url 'main:activity' %}">Recent Activities</a>
                    </div>
                </div>
                
                <div class="roomList__header">
                    <div>
                    <h2>Study Room</h2>
                    <p>{{room_count}} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'main:create-room' %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>add</title>
                        <path
                        d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                        ></path>
                    </svg>
                    Create Room
                    </a>                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                </div>

                {% include 'main/feed_component.html' %}                                                                        
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'main/activity_component.html' %}
            <!-- Activities End -->
        </div>
    </main>

{% endblock %}

main/templates/main/room.html
{% extends 'base.html' %}

{% block content %}
  <main class="profile-page layout layout--2">
    <div class="container">
      <!-- Room Start -->
      <div class="room">
        <div class="room__top">
          <div class="room__topLeft">
            <a href="{% url 'main:home' %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                ></path>
              </svg>
            </a>
            <h3>Study Room</h3>
          </div>

          {% if request.user == room.host %}
            <div class="room__topRight">
              <a href="{% url 'main:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24"
                  height="32"
                  viewBox="0 0 24 24"
                  width="32"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"
                      />
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"
                      />
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'main:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                  ></path>
                </svg>
              </a>
            </div>
          {% endif %}

          <!-- <button class="action-button" data-id="120" data-delete-url="https://randomuser.me/api/3324923"
          data-edit-url="profile.html">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>ellipsis-horizontal</title>
            <path
              d="M16 7.843c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 1.98c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
            <path
              d="M16 19.908c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 14.046c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
            <path
              d="M16 31.974c-2.156 0-3.908-1.753-3.908-3.908s1.753-3.908 3.908-3.908c2.156 0 3.908 1.753 3.908 3.908s-1.753 3.908-3.908 3.908zM16 26.111c-1.077 0-1.954 0.877-1.954 1.954s0.877 1.954 1.954 1.954c1.077 0 1.954-0.877 1.954-1.954s-0.877-1.954-1.954-1.954z">
            </path>
          </svg>
        </button> -->
        </div>
        <div class="room__box scroll">
          <div class="room__header scroll">
            <div class="room__info">
              <h3>{{room.name}}</h3>
              <span>{{room.created|timesince}} ago</span>
            </div>
            <div class="room__hosted">
              <p>Hosted By</p>
              <a href="{% url 'main:user-profile' room.host.username %}" class="room__author">
                <div class="avatar avatar--small">
                  <img src="{{room.host.image.url}}" />
                </div>
                <span>@{{room.host.username}}</span>
              </a>
            </div>
            <!-- <div class="room__details">
              {{room.description}}
            </div> -->
            <span class="room__topics">{{room.topic}}</span>
          </div>
          <div class="room__conversation">
            <div class="threads scroll">
              {% for message in room_messages %}
                  <div class="thread">
                    <div class="thread__top">
                      <div class="thread__author">
                        <a href="{% url 'main:user-profile' message.user.username %}" class="thread__authorInfo">
                          <div class="avatar avatar--small">
                            <img src="{{message.user.image.url}}" />
                          </div>
                          <span>@{{message.user.username}}</span>
                        </a>
                        <span class="thread__date">{{message.created|timesince}} ago</span>
                      </div>
                      {% if request.user == message.user %}
                        <a href="{% url 'main:delete-message' message.id %}">
                          <div class="thread__delete">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                              <title>remove</title>
                              <path
                                d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                              ></path>
                            </svg>
                          </div>
                        </a>
                          
                      {% endif %}
                    </div>
                    <div class="thread__details">
                      {{message.body}}
                    </div>
                  </div>
              {% endfor %}
              
              
            </div>
          </div>
        </div>
        
        <div class="room__message">
          <form action="." method="POST">{% csrf_token %}<input name="body" placeholder="Write your message here..." /></form>
        </div>
      </div>
      <!-- Room End -->

      <!--   Start -->
      <div class="participants">
        <h3 class="participants__top">Participants <span>({{participants.count}} Joined)</span></h3>
        <div class="participants__list scroll">
          {% for user in participants %}
            <a href="{% url 'main:user-profile' user.username %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="{{user.image.url}}" />
              </div>
              <p>
                {{user.username}}
                <span>@{{user.username}}</span>
              </p>
            </a>
            
          {% endfor %}
          
          
        </div>
      </div>
      <!--  End -->
    </div>
  </main>
{% endblock %}
    





    
    
  
    <div class="room-container">
        <div>
            <h2>{{room.name}}</h2>
            <p>{{room.description}}</p>
            <div class="comment-wrapper">
                <h4>Conversation</h4>
                <hr>
                {% for message in room_messages %}
                    <div>
                        {% if request.user == room.host or request.user == message.user %}
                            <a href="{% url 'main:delete-message' message.id %}">Delete</a>
                        {% endif %}
                        <small>@{{message.user}}   {{message.updated|timesince}} ago</small>
                        <p>{{message.body}}</p>
                        <hr>
                        
                    </div>
                {% endfor %}
                
                
            </div>
            {% if request.user.is_authenticated %}
                <div class="comment-form">
                    <form action="." method="POST">
                        {% csrf_token %}
                        <input type="text" name="body" placeholder="Write your message here...">
                    </form>
                </div>
            {% endif %}
        </div>

        <div>
            <h3>Participants</h3>
            <hr>
            {% for user in participants %}
                <div>
                    <p>@{{user.username}}</p>
                </div>
            
            {% endfor %}
        </div>
    </div>
        
    