core/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('api/', include('main.api.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<int:pk>/', views.getRoom)
]

main/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static

app_name='main'
urlpatterns = [
    path('login/', LoginView.as_view(), name = 'login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('register/', RegisterView.as_view(), name = 'register'),
    path('home/', HomeView.as_view(), name='home'), 
    # path('contact/', contact, name='contact'),
    path('room/<str:room_name>/', RoomView.as_view(), name='view-room'),
    path('create-room/', createRoom.as_view(), name = 'create-room'),
    path('update-room/<int:pk>/', updateRoom.as_view(), name = 'update-room'),
    path('delete-room/<int:pk>/', deleteRoom.as_view(), name = 'delete-room'),
    path('delete-message/<int:pk>/', deleteMessage.as_view(), name = 'delete-message'),
    path('profile/<str:username>/', UserProfile.as_view(), name = 'user-profile'), 
    path('update-profile/', updateUser.as_view(), name='update-profile'),
    path('topics/', TopicsView.as_view(), name='topics'),
    path('activity/', ActivityView.as_view(), name='activity'),
    # path('search/', search_results, name='ajax-search'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext as _

# Create your models here.

class User(AbstractUser):
    # username = models.CharField(max_length = 50)
    name = models.CharField(max_length = 100)
    # email = models.EmailField()
    bio = models.TextField(null=True, blank=True)
    # whenever you specify a default, django looks in the MEDIA_URL directory (which usually is the last bit of the url in the MEDIA_ROOT setting) 
    # the media url is the starting url for the links to the images displayed on the site and it can be named anything 
    # the media url gets its files from the media_root directory, but the name itself is what gets displayed in the urlbar in the website
    # in the settings which is currently 'media/' in the base directory.
    # django starts there and in the case below, we tell django to go further into 'user_images/' to get the image.
    image = models.ImageField(_('avatar'), upload_to = 'user_images', blank=True, null=True, default = 'user_images/default.png')

class Topic(models.Model):
    name = models.CharField(max_length = 200)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, related_name='owned_rooms')
    topic = models.ForeignKey(Topic, on_delete = models.SET_NULL, null = True, related_name = 'discussed_in')
    name = models.CharField(max_length=200)
    description = models.TextField(null = True, blank = True)
    participants = models.ManyToManyField(User, related_name='joined_rooms', blank=True)
    updated = models.DateTimeField(auto_now = True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE, related_name = 'messages')
    room = models.ForeignKey(Room, on_delete = models.CASCADE, related_name = 'messages')
    body = models.TextField()
    updated = models.DateTimeField(auto_now =True)
    created = models.DateTimeField(auto_now_add = True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.body[:50]}..."  if len(self.body) > 50 else self.body                           

main/forms.py
from  django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']

class MyUserCreationForm(UserCreationForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['image', 'name', 'username', 'email', 'bio', 'password1', 'password2']


class MyUserUpdateForm(forms.ModelForm):
    # password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['image', 'name', 'username', 'email', 'bio']

main/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from main.models import Room
from .serializers import RoomSerializer

# this decorator allows us to use the django rest framework for this view
@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id' 
    ]
    return  Response(routes)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)

@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Topic, Message, Room, User
from django.views.generic import *
from .forms import *
from django.urls import reverse
from django.db.models import Q
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.http import JsonResponse

# Create your views here.

class LoginView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('main:home'))
        return render(request, 'main/login-register.html', {'action':'login'})
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username = username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, f'You have logged in successfully as {request.user}')
        else:
            messages.error(request, 'username or pasword does not exist')
        # print(request.META['HTTP_REFERER'])
        return redirect(reverse('main:home'))

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('main:home'))

class RegisterView(View):
    def get(self, request):
        return render(request, 'main/login-register.html', {'action':'register', 'form':MyUserCreationForm()})
    def post(self, request):
        print(request.POST)
        #! always remember to pass in request.FILES when submitting forms that have an Imagefield or any type of filefield
        # ! attached to them
        form = MyUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            # user.username = user.username.lower()
            user.save()
            login(request, user)
        else:
            messages.error(request, 'An error occured during registration')
        return redirect(reverse('main:home'))
        
class RoomView(View):
    def get(self, request, room_name):
        room = Room.objects.get(name=room_name)
        room_messages = room.messages.all()
        participants = room.participants.all()
        return render(request, 'main/room.html', {'room':room, 'room_messages':room_messages, 'participants':participants})
    def post(self, request, room_name):
        room = Room.objects.get(name=room_name)
        message = Message.objects.create(
            user=request.user,
            room = room,
            body = request.POST.get('body'),
        )
        room.participants.add(request.user)
        messages.success(request, 'Your message has been posted successfully!')
        return self.get(request, room_name=room.name)

class HomeView(View):
    template_name = 'main/home.html'
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        rooms = Room.objects.filter(Q(name__icontains=q) | Q(topic__name__icontains=q) | Q(host__username__icontains=q))[:6] 
        messages = Message.objects.filter(Q(room__in=rooms) | Q(room__topic__name__icontains=q))[:5]
        context = {'rooms': rooms, 'activity':messages, 'room_count':len(rooms), 'topics':Topic.objects.all()[:5]}
        return render(request, 'main/home.html', context)

class UserProfile(View):
    def get(self, request, username):
        user = User.objects.get(username=username)
        rooms = user.owned_rooms.all()
        user_messages = user.messages.all()[:5]
        context = {'user':user, 'topics':Topic.objects.all()[:5], 'rooms':rooms, 'activity':user_messages}
        return render(request, 'main/profile.html', context)

class createRoom(LoginRequiredMixin, View):
    def get(self, request):
        context = {'form':RoomForm(), 'action':'create', 'topics':Topic.objects.all()}
        return render(request, 'main/cr_ud-room.html', context)
    def post(self, request, *args, **kwargs):
        topic, created = Topic.objects.get_or_create(name=request.POST.get('topic'))
        Room.objects.create(
            host = request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description')
        )
        # form = RoomForm(request.POST)
        # if form.is_valid():
        #     new_room = form.save(commit=False)
        #     new_room.host = request.user
        #     new_room.save()
        return redirect(reverse('main:home'))

class updateRoom(LoginRequiredMixin, View):
    def get(self, request, pk):
        room = get_object_or_404(Room, id = self.kwargs.get('pk'))
        if request.user != room.host:
            return HttpResponse(f"You are not allowed to edit '<i>{room}</i>' , it belongs to @{room.host.username}")

        form = RoomForm(instance=room)
        
        return render(request, 'main/cr_ud-room.html', {'form':form, 'room':room, 'action':'update', 'topics':Topic.objects.all()})
    def post(self, request, pk): 
        room = get_object_or_404(Room, id = self.kwargs.get('pk'))
        topic, created = Topic.objects.get_or_create(name=request.POST.get('topic'))
        room.topic = topic
        room.name = request.POST.get('name')
        room.description = request.POST.get('description')
        room.save()
        return redirect('main:view-room', room.name)

class deleteRoom(LoginRequiredMixin, View):
    template_name = 'main/delete_form.html'
    def get(self, request, pk):
        room = get_object_or_404(Room, id=pk)
        if request.user != room.host:
            return HttpResponse(f"You are not allowed to delete '<i>{room}</i>' , it belongs to @{room.host.username}")
        return render(request, 'main/delete.html', {'object':room})
    def post(self, request, pk):
        room = get_object_or_404(Room, id=pk)
        room.delete()
        return redirect(reverse('main:home'))

class deleteMessage(LoginRequiredMixin, View):
    template_name = 'main/delete_form.html'
    def get(self, request, pk):
        message = get_object_or_404(Message, id=pk)
        if request.user != message.user and request.user != message.room.host :
            return HttpResponse(f"You are not allowed to delete '<i>{message}</i>' , it belongs to @{message.user.username}")
        return render(request, 'main/delete.html', {'object':message})
    def post(self, request, pk):
        message = get_object_or_404(Message, id=pk)
        room = message.room
        if not room.messages.filter(user=message.user):
            room.participants.remove(message.user) 
        message.delete()
        return redirect(reverse('main:view-room', kwargs = {'room_name':room.name}))

class updateUser(LoginRequiredMixin, View):
    def get(self, request):
        form = MyUserUpdateForm(instance=request.user)
        print(form)
        return render(request, 'main/update-user.html', {'form':form})
    def post(self, request):
        form = MyUserUpdateForm(request.POST, request.FILES, instance=request.user)
        print(form)
        if form.is_valid():
            form.save()
        return redirect(reverse('main:user-profile', kwargs={'username':request.user.username}))
        
class TopicsView(View):
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        topics = Topic.objects.filter(Q(name__icontains=q))
        return render(request, 'main/topics.html', {'topics':topics})

class ActivityView(View):
    def get(self, request):
        q = request.GET.get('q') if request.GET.get('q') else ''
        rooms = Room.objects.filter(Q(name__icontains=q) | Q(topic__name__icontains=q) | Q(host__username__icontains=q))[:6] 
        activity = Message.objects.filter(Q(room__in=rooms) | Q(room__topic__name__icontains=q))[:5]
        return render(request, 'main/activity.html', {'activity':activity})

"""
class createRoom2(CreateView):
    template_name = 'main/room_form.html'
    form_class = RoomForm
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('main:home')

class updateRoom2(UpdateView):
    template_name = 'main/create-room.html'
    form_class = RoomForm
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    def get_object(self):
        return get_object_or_404(Room, id = self.kwargs.get('pk'))
    def get_success_url(self):
        return reverse('main:home')
"""

main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'assets/favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>StudyBuddy - Find study partners around the world!</title>
  </head>

  <body>
    {% include 'navbar.html' %}
    
    {% block content %}

    {% endblock %}

    <script src="{% static 'js/script.js' %}"></script>
  </body>
</html>










    
    
    
    
<!--     
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StydyBud course</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
</head>
<body>
    <ul>
        <li><a href="{% url 'main:home' %}">Home</a></li>
        <li><a href="">Contact</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'main:logout' %}">Logout</a></li>
        {% else %}
            <li><a href="{% url 'main:login' %}">Login</a></li>
        {% endif %}
        <li><a href="{% url 'main:register' %}">Register</a></li>
    </ul>
    
    {% if messages %}
        <ul class="messsages">
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="{% url 'main:home' %}" method="GET" >
        <input type="text" name="q" placeholder = 'Search Rooms...' autocomplete='off'>
    </form>
    <hr>
    
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html> -->

main/templates/navbar.html
{% load static %}

<header class="header header--loggedIn">
    <div class="container">
      <a href="{% url 'main:home' %}" class="header__logo">
        <img src="{% static 'assets/logo.svg' %}" />
        <h1>StudyBuddy</h1>
      </a>
      <form class="header__search" action="{% url 'main:home' %}" method="GET" >
        <label>
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>search</title>
            <path
              d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
            ></path>
          </svg>
          
          <input type="text" name="q" placeholder = 'Search Rooms...' autocomplete='off'>
        </label>
      </form>
      <nav class="header__menu">
        

          

          {% if request.user.is_authenticated %}
            <!-- Logged In -->
            <div class="header__user">
              <a href="{% url 'main:user-profile' request.user.username %}">
                <div class="avatar avatar--medium active">
                  <img src="{{request.user.image.url}}" />
                </div>
                  <p>{{request.user.username}} <span><a href="{% url 'main:user-profile' request.user.username %}"></a>@{{request.user.username}}</span></p>
              </a>
              <button class="dropdown-button">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>chevron-down</title>
                  <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                </svg>
              </button>
            </div>
          {% else %}
            <!-- Not Logged In -->
            <a href="{% url 'main:login' %}">
              <img src="{% static 'assets/avatar.svg' %}" />
              <p>Login</p>
            </a>

          {% endif %}


        <div class="dropdown-menu">
          <a href="settings.html" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>tools</title>
              <path
                d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
              ></path>
            </svg>
            Settings</a
          >
          <a href="{% url 'main:update-profile' %}" class="dropdown-link"
            ><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>Update profile</title>
              <path
                d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z"
              ></path>
            </svg>
            Update profile</a
          >
            <a href="{% url 'main:logout' %}" class="dropdown-link">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>sign-out</title>
                <path d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z"></path>
                <path d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z"></path>
              </svg>
              logout
            </a>
          
            
        </div>
      </nav>
    </div>
</header>